from tkinter import *

def click(event):
    global scvalue
    text = event.widget.cget("text")
    if text =="=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            value = eval(scvalue.get())
        scvalue.set(value)
        screen.update()
    elif text == "C":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()

root = Tk()
root.title("Calculator")
root.geometry("350x500")
root.wm_iconbitmap("1.png")

scvalue = StringVar()
scvalue.set("")
screen = Entry(root,textvariable=scvalue,font="lucida 20 bold")
screen.pack(fill=X,ipadx=8,padx=10,pady=10)

f = Frame(root,bg="grey")
b = Button(f,text="7",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="8",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="9",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="+",font="lucida 20 bold",padx=10,pady=10,width=60)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
f.pack(fill=X)

f = Frame(root,bg="grey")
b = Button(f,text="4",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="5",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="6",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="-",font="lucida 20 bold",padx=10,pady=10,width=60)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
f.pack(fill=X)

f = Frame(root,bg="grey")
b = Button(f,text="1",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="2",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="3",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="*",font="lucida 20 bold",padx=10,pady=10,width=60)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
f.pack(fill=X)

f = Frame(root,bg="grey")
b = Button(f,text="C",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="0",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text=".",font="lucida 20 bold",padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="/",font="lucida 20 bold",padx=10,pady=10,width=60)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
f.pack(fill=X)

f = Frame(root,bg="grey")
b = Button(f,text="=",font="lucida 20 bold",padx=10,pady=10,width=11)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b = Button(f,text="%",font="lucida 20 bold",padx=10,pady=10,width=60)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
f.pack(fill=X)


root.mainloop()
